"""generate.py -- seeded synthetic generator for Cascadia Revenue Assurance.

    ALL DATA IN THIS REPOSITORY IS SYNTHETIC. It is generated by this file
    from a fixed seed. There is no real company, customer, partner, product
    or person anywhere in it, and there never will be. Every figure the
    module publishes traces back to the parameter block below.

What this file does
    Simulates what customers ASK FOR -- it emits order transactions. It does
    not, anywhere, compute what a customer is billable for. Effective
    quantities, term boundaries, accepted/rejected flags and every derived
    row are the engines' to produce from the event stream and the rules in
    governance/entitlement-rules.md. The generator knows only the register:
    the last quantity each customer requested, and whether they cancelled.

Outputs (data/raw/ is the frozen snapshot; see governance/freeze.toml)
    data/raw/customers.csv                one row per customer
    data/raw/subscriptions_register.csv   one row per subscription, register
                                          attributes as of the as-of date
    data/raw/order_events.csv             one row per transaction received
    data/raw/manifest.json                seed, window, parameters, counts
    governance/generator_assumptions.md   the disclosure, the parameter block,
                                          the realised mix beside the design

Determinism
    One random.Random(SEED). Customers, months and subscriptions are iterated
    in fixed order; no set iteration anywhere. transaction_id is assigned
    AFTER sorting every transaction by (received_date, generation order), so
    it is monotonic in date -- D9 depends on that. The same seed reproduces
    byte-identical files, and src/validate.py proves it by regenerating into
    a temporary folder and diffing.

Usage
    python src/generate.py
"""

from __future__ import annotations

import calendar
import csv
import json
import math
import random
import sys
from datetime import date, timedelta
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

REPO_ROOT = Path(__file__).resolve().parent.parent
RAW_DIR = REPO_ROOT / "data" / "raw"
ASSUMPTIONS_PATH = REPO_ROOT / "governance" / "generator_assumptions.md"

GENERATOR_VERSION = "1.0.0"

# ===========================================================================
# PARAMETER BLOCK -- every tunable assumption, in one place (D11).
# ===========================================================================

SEED = 20260911                       # fixed seed; same seed => byte-identical files
AS_OF = date(2026, 6, 30)             # the "today" the register describes
WINDOW_START = date(2024, 7, 1)       # first possible opening date
WINDOW_END = date(2026, 6, 30)        # last possible transaction date (24 months)

DISCLOSURE = ("Synthetic data from a seeded generator (seed %d). Simulated: "
              "not a real company, customer, partner, product or book of business."
              % SEED)

# --- population --------------------------------------------------------------
N_CUSTOMERS = 4_000
N_DIRECT = 200                        # the rest are Partner
PARTNERS = [                          # partner_id, invented name, share of Partner customers
    ("P1", "Ochre Basalt Partners", 0.55),
    ("P2", "Teal Gypsum Channel", 0.30),
    ("P3", "Umber Quartz Resale", 0.15),
]
DIRECT_ID = "DIRECT"
DIRECT_NAME = "Direct (no partner)"

P_ANNUAL = 0.60                       # term mix; the rest monthly
P_SECOND_SUBSCRIPTION = 0.10          # customers who open a second subscription later

# --- licence counts (log-normal, then clamped) ---------------------------------
PARTNER_QTY_MEDIAN, PARTNER_QTY_SIGMA, PARTNER_QTY_RANGE = 8, 0.90, (1, 80)
DIRECT_QTY_MEDIAN, DIRECT_QTY_SIGMA, DIRECT_QTY_RANGE = 200, 0.70, (25, 2_000)

# --- monthly movement, per active subscription-month (D11) ---------------------
P_ADD = 0.030
P_REDUCE = 0.020
P_CANCEL = 0.010
P_REJECT = 0.005                      # a transaction the rules will refuse
ADD_UPLIFT = (1.10, 1.60)             # multiplier on the register quantity, min +1
REDUCE_FACTOR = (0.40, 0.90)          # multiplier on the register quantity, min 1

# The kind of refused transaction, when one is rolled. Two mixes, because the
# after-cancel reasons need a cancelled subscription to exist.
REJECT_MIX_ACTIVE = [                 # on a subscription that is still active
    ("NOOP_QUANTITY", 0.45),
    ("REDUCE_TO_ZERO", 0.25),
    ("DUPLICATE_NEW", 0.15),
    ("UNKNOWN_SUBSCRIPTION", 0.15),
]
REJECT_MIX_CANCELLED = [              # on a subscription cancelled recently
    ("ADD_AFTER_CANCEL", 0.40),
    ("REDUCE_AFTER_CANCEL", 0.40),
    ("DUPLICATE_CANCEL", 0.20),
]
AFTER_CANCEL_MONTHS = 3               # how long a cancelled key keeps attracting rejects

UNKNOWN_KEY_BASE = 90_000             # subscription numbers never issued

# ===========================================================================
# helpers
# ===========================================================================


def month_end(d: date) -> date:
    return date(d.year, d.month, calendar.monthrange(d.year, d.month)[1])


def months_in_window() -> list[date]:
    """First day of every month from WINDOW_START through WINDOW_END."""
    out, d = [], date(WINDOW_START.year, WINDOW_START.month, 1)
    while d <= WINDOW_END:
        out.append(d)
        d = date(d.year + (d.month == 12), d.month % 12 + 1, 1)
    return out


def weighted_choice(rng: random.Random, pairs: list[tuple[str, float]]) -> str:
    r, acc = rng.random(), 0.0
    for name, w in pairs:
        acc += w
        if r < acc:
            return name
    return pairs[-1][0]


def lognormal_int(rng: random.Random, median: float, sigma: float, lo: int, hi: int) -> int:
    v = int(round(math.exp(rng.gauss(math.log(median), sigma))))
    return max(lo, min(hi, v))


def random_day(rng: random.Random, first: date, last: date) -> date:
    return first + timedelta(days=rng.randint(0, (last - first).days))


# ===========================================================================
# the simulation
# ===========================================================================


class Sub:
    __slots__ = ("key", "customer_key", "partner_id", "channel", "term_type",
                 "opened", "register_qty", "status", "status_date", "cancel_month")

    def __init__(self, key, customer_key, partner_id, channel, term_type, opened, qty):
        self.key = key
        self.customer_key = customer_key
        self.partner_id = partner_id
        self.channel = channel
        self.term_type = term_type
        self.opened = opened
        self.register_qty = qty
        self.status = "active"
        self.status_date = opened
        self.cancel_month = None


def simulate(rng: random.Random) -> dict:
    # --- customers --------------------------------------------------------------
    n_partner = N_CUSTOMERS - N_DIRECT
    partner_counts = {}
    remaining = n_partner
    for i, (pid, _name, share) in enumerate(PARTNERS):
        n = remaining if i == len(PARTNERS) - 1 else int(round(n_partner * share))
        partner_counts[pid] = n
        remaining -= n
    assignment = []
    for pid, _n, _s in PARTNERS:
        assignment += [pid] * partner_counts[pid]
    assignment += [DIRECT_ID] * N_DIRECT
    rng.shuffle(assignment)           # so customer_key does not encode the partner

    customers, ref_counter = [], {pid: 0 for pid, _n, _s in PARTNERS}
    ref_counter[DIRECT_ID] = 0
    for i, pid in enumerate(assignment, start=1):
        ref_counter[pid] += 1
        customers.append({
            "customer_key": f"C{i:05d}",
            "partner_id": pid,
            # Partner-scoped, zero-padded, and deliberately NOT unique across
            # partners: ref 00001 exists under every partner and under Direct.
            "customer_ref": f"{ref_counter[pid]:05d}",
            "channel": "direct" if pid == DIRECT_ID else "partner",
        })

    # --- subscriptions ------------------------------------------------------------
    subs: list[Sub] = []
    events: list[dict] = []           # raw transactions, generation order
    intended_rejects: dict[str, int] = {}
    seq = 0

    def emit(received: date, key: str, ttype: str, qty: int, term_type: str, source: str):
        nonlocal seq
        seq += 1
        events.append({
            "_seq": seq, "received_date": received, "subscription_key": key,
            "transaction_type": ttype, "requested_quantity": qty,
            "term_type": term_type, "source": source,
        })

    def open_subscription(cust: dict, opened: date) -> Sub:
        term_type = "annual" if rng.random() < P_ANNUAL else "monthly"
        if cust["channel"] == "direct":
            qty = lognormal_int(rng, DIRECT_QTY_MEDIAN, DIRECT_QTY_SIGMA, *DIRECT_QTY_RANGE)
        else:
            qty = lognormal_int(rng, PARTNER_QTY_MEDIAN, PARTNER_QTY_SIGMA, *PARTNER_QTY_RANGE)
        sub = Sub(f"S{len(subs) + 1:05d}", cust["customer_key"], cust["partner_id"],
                  cust["channel"], term_type, opened, qty)
        subs.append(sub)
        emit(opened, sub.key, "NEW", qty, term_type, source_of(sub))
        return sub

    def source_of(sub: Sub) -> str:
        return "contract_record" if sub.channel == "direct" else "partner_api_order"

    for cust in customers:
        opened = random_day(rng, WINDOW_START, WINDOW_END)
        open_subscription(cust, opened)
        if rng.random() < P_SECOND_SUBSCRIPTION:
            earliest = opened + timedelta(days=30)
            if earliest <= WINDOW_END:
                open_subscription(cust, random_day(rng, earliest, WINDOW_END))

    # --- monthly movement ----------------------------------------------------------
    active_sub_months = 0
    for m0 in months_in_window():
        m1 = min(month_end(m0), WINDOW_END)
        for sub in subs:
            if sub.opened > m1:
                continue
            first_day = max(m0, sub.opened + timedelta(days=1))
            if first_day > m1:
                continue                          # opened on the month's last day

            if sub.status == "cancelled":
                months_since = (m0.year - sub.cancel_month.year) * 12 + (m0.month - sub.cancel_month.month)
                if 0 <= months_since <= AFTER_CANCEL_MONTHS and rng.random() < P_REJECT:
                    reason = weighted_choice(rng, REJECT_MIX_CANCELLED)
                    d = random_day(rng, max(first_day, sub.status_date + timedelta(days=1)), m1) \
                        if sub.status_date < m1 else None
                    if d is None:
                        continue
                    if reason == "ADD_AFTER_CANCEL":
                        emit(d, sub.key, "ADD", max(2, sub.register_qty + 1) if sub.register_qty else 5, "", source_of(sub))
                    elif reason == "REDUCE_AFTER_CANCEL":
                        emit(d, sub.key, "REDUCE", 1, "", source_of(sub))
                    else:
                        emit(d, sub.key, "CANCEL", 0, "", source_of(sub))
                    intended_rejects[reason] = intended_rejects.get(reason, 0) + 1
                continue

            active_sub_months += 1
            r = rng.random()
            d = random_day(rng, first_day, m1)
            R = sub.register_qty
            if r < P_ADD:
                q = max(R + 1, int(round(R * rng.uniform(*ADD_UPLIFT))))
                emit(d, sub.key, "ADD", q, "", source_of(sub))
                sub.register_qty = q
            elif r < P_ADD + P_REDUCE:
                if R > 1:
                    q = min(R - 1, max(1, int(math.floor(R * rng.uniform(*REDUCE_FACTOR)))))
                    emit(d, sub.key, "REDUCE", q, "", source_of(sub))
                    sub.register_qty = q
            elif r < P_ADD + P_REDUCE + P_CANCEL:
                emit(d, sub.key, "CANCEL", 0, "", source_of(sub))
                sub.register_qty = 0
                sub.status = "cancelled"
                sub.status_date = d
                sub.cancel_month = m0
            elif r < P_ADD + P_REDUCE + P_CANCEL + P_REJECT:
                reason = weighted_choice(rng, REJECT_MIX_ACTIVE)
                if reason == "NOOP_QUANTITY":
                    emit(d, sub.key, "ADD", R, "", source_of(sub))
                elif reason == "REDUCE_TO_ZERO":
                    emit(d, sub.key, "REDUCE", 0, "", source_of(sub))
                elif reason == "DUPLICATE_NEW":
                    emit(d, sub.key, "NEW", max(1, R), sub.term_type, source_of(sub))
                else:
                    unknown = f"S{UNKNOWN_KEY_BASE + rng.randint(1, 999):05d}"
                    emit(d, unknown, "ADD" if rng.random() < 0.5 else "REDUCE",
                         rng.randint(1, 20), "", "partner_api_order")
                intended_rejects[reason] = intended_rejects.get(reason, 0) + 1
            # else: flat

    # --- assign monotonic transaction ids -------------------------------------------
    events.sort(key=lambda e: (e["received_date"], e["_seq"]))
    for i, e in enumerate(events, start=1):
        e["transaction_id"] = i

    return {
        "customers": customers,
        "subs": subs,
        "events": events,
        "partner_counts": partner_counts,
        "active_sub_months": active_sub_months,
        "intended_rejects": dict(sorted(intended_rejects.items())),
    }


# ===========================================================================
# writers
# ===========================================================================


def write_csv(path: Path, rows: list[dict], columns: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh, lineterminator="\n")
        w.writerow(columns)
        for r in rows:
            w.writerow([_fmt(r[c]) for c in columns])


def _fmt(v):
    if isinstance(v, date):
        return v.isoformat()
    if isinstance(v, bool):
        return "true" if v else "false"
    return "" if v is None else v


def generate(raw_dir: Path = RAW_DIR, assumptions_path: Path | None = ASSUMPTIONS_PATH) -> dict:
    rng = random.Random(SEED)
    sim = simulate(rng)
    customers, subs, events = sim["customers"], sim["subs"], sim["events"]

    write_csv(raw_dir / "customers.csv", customers,
              ["customer_key", "partner_id", "customer_ref", "channel"])

    register_rows = [{
        "subscription_key": s.key, "customer_key": s.customer_key,
        "term_type": s.term_type, "opened_date": s.opened,
        "register_quantity": s.register_qty, "register_status": s.status,
        "register_status_date": s.status_date,
    } for s in subs]
    write_csv(raw_dir / "subscriptions_register.csv", register_rows,
              ["subscription_key", "customer_key", "term_type", "opened_date",
               "register_quantity", "register_status", "register_status_date"])

    write_csv(raw_dir / "order_events.csv", events,
              ["transaction_id", "received_date", "subscription_key", "transaction_type",
               "requested_quantity", "term_type", "source"])

    # --- counts for the manifest and the assumptions document ------------------------
    by_type = {}
    for e in events:
        by_type[e["transaction_type"]] = by_type.get(e["transaction_type"], 0) + 1
    by_type = dict(sorted(by_type.items()))
    n_annual = sum(1 for s in subs if s.term_type == "annual")
    n_cancelled = sum(1 for s in subs if s.status == "cancelled")
    asm = sim["active_sub_months"]
    intended = sim["intended_rejects"]
    n_rejects_intended = sum(intended.values())
    refs = {}
    for c in customers:
        refs[c["customer_ref"]] = refs.get(c["customer_ref"], 0) + 1
    refs_colliding = sum(1 for v in refs.values() if v > 1)

    parameters = {
        "SEED": SEED, "AS_OF": AS_OF.isoformat(),
        "WINDOW_START": WINDOW_START.isoformat(), "WINDOW_END": WINDOW_END.isoformat(),
        "N_CUSTOMERS": N_CUSTOMERS, "N_DIRECT": N_DIRECT,
        "PARTNERS": [{"partner_id": p, "partner_name": n, "share": s} for p, n, s in PARTNERS],
        "P_ANNUAL": P_ANNUAL, "P_SECOND_SUBSCRIPTION": P_SECOND_SUBSCRIPTION,
        "PARTNER_QTY": {"median": PARTNER_QTY_MEDIAN, "sigma": PARTNER_QTY_SIGMA, "range": PARTNER_QTY_RANGE},
        "DIRECT_QTY": {"median": DIRECT_QTY_MEDIAN, "sigma": DIRECT_QTY_SIGMA, "range": DIRECT_QTY_RANGE},
        "P_ADD": P_ADD, "P_REDUCE": P_REDUCE, "P_CANCEL": P_CANCEL, "P_REJECT": P_REJECT,
        "ADD_UPLIFT": ADD_UPLIFT, "REDUCE_FACTOR": REDUCE_FACTOR,
        "REJECT_MIX_ACTIVE": dict(REJECT_MIX_ACTIVE), "REJECT_MIX_CANCELLED": dict(REJECT_MIX_CANCELLED),
        "AFTER_CANCEL_MONTHS": AFTER_CANCEL_MONTHS, "UNKNOWN_KEY_BASE": UNKNOWN_KEY_BASE,
    }
    realised = {
        "active_subscription_months": asm,
        "rate_per_active_subscription_month": {
            "ADD": by_type.get("ADD", 0) - intended.get("NOOP_QUANTITY", 0) - intended.get("ADD_AFTER_CANCEL", 0)
                   - sum(1 for e in events if e["transaction_type"] == "ADD" and e["subscription_key"] not in {s.key for s in subs}),
            "REDUCE": by_type.get("REDUCE", 0) - intended.get("REDUCE_TO_ZERO", 0) - intended.get("REDUCE_AFTER_CANCEL", 0)
                      - sum(1 for e in events if e["transaction_type"] == "REDUCE" and e["subscription_key"] not in {s.key for s in subs}),
            "CANCEL": by_type.get("CANCEL", 0) - intended.get("DUPLICATE_CANCEL", 0),
            "REJECT": n_rejects_intended,
        },
    }
    for k in list(realised["rate_per_active_subscription_month"]):
        n = realised["rate_per_active_subscription_month"][k]
        realised["rate_per_active_subscription_month"][k] = {"count": n, "rate": round(n / asm, 5) if asm else None}

    manifest = {
        "module": "cascadia-revenue-assurance",
        "generator": "src/generate.py",
        "generator_version": GENERATOR_VERSION,
        "disclosure": DISCLOSURE,
        "seed": SEED,
        "as_of_date": AS_OF.isoformat(),
        "window": {"start": WINDOW_START.isoformat(), "end": WINDOW_END.isoformat()},
        "parameters": parameters,
        "counts": {
            "customers": len(customers),
            "customers_by_partner": {**sim["partner_counts"], DIRECT_ID: N_DIRECT},
            "customer_refs_shared_across_partners": refs_colliding,
            "subscriptions": len(subs),
            "subscriptions_annual": n_annual,
            "subscriptions_monthly": len(subs) - n_annual,
            "subscriptions_cancelled_by_as_of": n_cancelled,
            "transactions": len(events),
            "transactions_by_type": by_type,
            "transactions_intended_to_be_refused_by_reason": intended,
        },
        "realised_movement": realised,
        "files": ["customers.csv", "subscriptions_register.csv", "order_events.csv", "manifest.json"],
    }
    (raw_dir / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=False) + "\n",
                                           encoding="utf-8", newline="\n")

    if assumptions_path is not None:
        assumptions_path.parent.mkdir(parents=True, exist_ok=True)
        assumptions_path.write_text(render_assumptions(manifest), encoding="utf-8", newline="\n")
    return manifest


def render_assumptions(m: dict) -> str:
    p, c, r = m["parameters"], m["counts"], m["realised_movement"]
    rates = r["rate_per_active_subscription_month"]
    design = {"ADD": P_ADD, "REDUCE": P_REDUCE, "CANCEL": P_CANCEL, "REJECT": P_REJECT}
    partner_shares = " / ".join(f"{x['share']:.0%}" for x in p["PARTNERS"])
    lines = [
        "# Generator assumptions — Cascadia Revenue Assurance",
        "",
        f"*Auto-generated by `src/generate.py` v{GENERATOR_VERSION}. Seed **{m['seed']}**, "
        f"as-of **{m['as_of_date']}**, window **{m['window']['start']} → {m['window']['end']}**. "
        "Do not hand-edit; regenerate.*",
        "",
        f"> **{m['disclosure']}** Every customer, partner, subscription and transaction "
        "below was invented by this script from a fixed seed. No figure in this module "
        "may be read as a claim about any real book of business. Any resemblance to a "
        "real company, partner or person is unintended.",
        "",
        "## What the generator does, and does not, decide",
        "",
        "The generator simulates **customer intent** and emits **order transactions**. "
        "It tracks the register — the last quantity each customer asked for, and "
        "whether they cancelled — because a customer who adds licences is adding to "
        "what they last asked for. It never computes an effective quantity, a term "
        "boundary, a proration, or an accepted/rejected flag. Those belong to the "
        "engines and to `governance/entitlement-rules.md`. When the generator emits a "
        "transaction the rules will refuse, it does so deliberately, and it records "
        "only the *count* it intended, by reason, in `data/raw/manifest.json`, so "
        "`src/validate.py` can check that the engine refused exactly those.",
        "",
        "## Population",
        "",
        "| | |",
        "|---|---|",
        f"| Customers | **{c['customers']:,}** — {c['customers'] - p['N_DIRECT']:,} Partner, {p['N_DIRECT']:,} Direct |",
        "| Partners | " + "; ".join(f"`{x['partner_id']}` {x['partner_name']} ({x['share']:.0%})" for x in p["PARTNERS"]) + " — names invented |",
        f"| Customers by partner | " + ", ".join(f"`{k}` {v:,}" for k, v in c["customers_by_partner"].items()) + " |",
        f"| Subscriptions | **{c['subscriptions']:,}** — {c['subscriptions_annual']:,} annual, {c['subscriptions_monthly']:,} monthly ({c['subscriptions_annual'] / c['subscriptions']:.1%} annual against a design of {p['P_ANNUAL']:.0%}) |",
        f"| Cancelled by as-of | {c['subscriptions_cancelled_by_as_of']:,} |",
        f"| Transactions | **{c['transactions']:,}** — " + ", ".join(f"`{k}` {v:,}" for k, v in c["transactions_by_type"].items()) + " |",
        f"| `customer_ref` values shared across partners | {c['customer_refs_shared_across_partners']:,} — the natural-key hazard is deliberate; see the codebook |",
        "",
        "## Realised movement beside the designed band",
        "",
        "Rates are per **active subscription-month** — one roll per subscription per "
        "calendar month in which it was open and not yet cancelled. "
        f"There were **{r['active_subscription_months']:,}** such rolls.",
        "",
        "| Outcome | Designed | Realised count | Realised rate |",
        "|---|---:|---:|---:|",
    ]
    for k in ("ADD", "REDUCE", "CANCEL", "REJECT"):
        lines.append(f"| `{k}` | {design[k]:.1%} | {rates[k]['count']:,} | {rates[k]['rate']:.2%} |")
    lines += [
        "",
        "`REDUCE` realises slightly under design because a subscription at one "
        "licence cannot reduce and stays flat instead. Refused transactions are "
        "counted here by the generator's intent; the engine's own classification is "
        "in `fact_order_event` and the two are reconciled by `src/validate.py`.",
        "",
        "Refused transactions intended, by reason: "
        + ", ".join(f"`{k}` {v:,}" for k, v in c["transactions_intended_to_be_refused_by_reason"].items()) + ".",
        "",
        "## Parameter block",
        "",
        "Every tunable assumption, as set for this run. These are arbitrary and are "
        "disclosed rather than defended.",
        "",
        "| Parameter | Value | What it controls |",
        "|---|---|---|",
        f"| `SEED` | {p['SEED']} | Fixed seed; the same seed reproduces byte-identical files |",
        f"| `WINDOW_START` / `WINDOW_END` | {p['WINDOW_START']} / {p['WINDOW_END']} | Openings and transactions fall inside this window |",
        f"| `AS_OF` | {p['AS_OF']} | The date every measure is stated at |",
        f"| `N_CUSTOMERS` / `N_DIRECT` | {p['N_CUSTOMERS']:,} / {p['N_DIRECT']:,} | Size of the book; Direct is the small, large-licence channel |",
        f"| `PARTNERS` shares | {partner_shares} | Unequal partner shares of the Partner customers |",
        f"| `P_ANNUAL` | {p['P_ANNUAL']:.0%} | Share of subscriptions on an annual term |",
        f"| `P_SECOND_SUBSCRIPTION` | {p['P_SECOND_SUBSCRIPTION']:.0%} | Customers who open a second subscription at least 30 days later |",
        f"| `PARTNER_QTY` | median {p['PARTNER_QTY']['median']}, sigma {p['PARTNER_QTY']['sigma']}, clamp {p['PARTNER_QTY']['range']} | Opening licence count, Partner (log-normal) |",
        f"| `DIRECT_QTY` | median {p['DIRECT_QTY']['median']}, sigma {p['DIRECT_QTY']['sigma']}, clamp {p['DIRECT_QTY']['range']} | Opening licence count, Direct (log-normal) |",
        f"| `P_ADD` / `P_REDUCE` / `P_CANCEL` / `P_REJECT` | {p['P_ADD']:.1%} / {p['P_REDUCE']:.1%} / {p['P_CANCEL']:.1%} / {p['P_REJECT']:.1%} | Per active subscription-month; the rest flat |",
        f"| `ADD_UPLIFT` | {p['ADD_UPLIFT']} | An `ADD` asks for the register times this, at least +1 |",
        f"| `REDUCE_FACTOR` | {p['REDUCE_FACTOR']} | A `REDUCE` asks for the register times this, at least 1, always below the register |",
        f"| `REJECT_MIX_ACTIVE` | {p['REJECT_MIX_ACTIVE']} | Which refusal an active subscription attracts |",
        f"| `REJECT_MIX_CANCELLED` | {p['REJECT_MIX_CANCELLED']} | Which refusal a recently cancelled subscription attracts |",
        f"| `AFTER_CANCEL_MONTHS` | {p['AFTER_CANCEL_MONTHS']} | How many months after a cancel a key still attracts refusals |",
        f"| `UNKNOWN_KEY_BASE` | {p['UNKNOWN_KEY_BASE']} | Subscription numbers from here up are never issued; an `UNKNOWN_SUBSCRIPTION` names one |",
        "",
        "## Why the shape is what it is",
        "",
        "- **Openings are uniform across the whole window**, as the brief asked, so "
        "annual renewals occur inside it for roughly half the annual book and the "
        "other half is still in its first term at the as-of date. No opening book "
        "was front-loaded; that would have been an assumption the brief did not make.",
        "- **An `ADD` is sized against the register**, because the register is what the "
        "customer believes they have. When a reduction is pending, an add can "
        "therefore land between the register and the effective quantity; rule 4.2 "
        "in the rules document says what happens then, and G13 tests it.",
        "- **A `CANCEL` sets the register quantity to 0** on the day it is received. "
        "The subscription stays billable to term end. That is the module's largest "
        "single source of gap and it is a consequence of the rules, not of the "
        "generator.",
        "- **Nothing here is drawn from, calibrated to, or shaped after any real "
        "company's data.** The parameters were chosen to make the rules' consequences "
        "visible, and are disclosed for that reason.",
        "",
        f"*{m['disclosure']} Generated by `src/generate.py` v{GENERATOR_VERSION} at seed {m['seed']}. "
        "Regenerating is a deliberate act (PRINCIPLES rule 1); the freeze gate "
        "`src/validate_freeze.py` refuses any other change to `data/raw/`.*",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    m = generate()
    c = m["counts"]
    print(f"generate.py v{GENERATOR_VERSION} seed {SEED}: "
          f"{c['customers']:,} customers, {c['subscriptions']:,} subscriptions, "
          f"{c['transactions']:,} transactions -> {RAW_DIR.relative_to(REPO_ROOT).as_posix()}/")
    print(f"  by type: {c['transactions_by_type']}")
    print(f"  intended refusals: {c['transactions_intended_to_be_refused_by_reason']}")
    print(f"  wrote {ASSUMPTIONS_PATH.relative_to(REPO_ROOT).as_posix()}")
    print(f"  {DISCLOSURE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
