#!/usr/bin/env python3
"""validate_freeze.py — freeze-integrity gate, shared across Cascadia modules.

    cascadia-standards template v1.0.0
    Copied verbatim into each module repo. Do not edit this file in a module.
    Everything module-specific lives in governance/freeze.toml.

A Cascadia data module publishes figures with an "as-of" date, and that date is
a claim made out loud — in a portfolio page, in an interview. This script is
what turns "the build did not touch the frozen snapshot" from a promise into a
verified assertion, the same way the whitespace hook in the website repo turns
a remembered rule into a structural one.

It checks one thing, thoroughly:

    every path the module declares frozen is byte-identical to the baseline,
    except for paths it explicitly declared as permitted edits — and those are
    printed with their stated reason, so an exception is never silent.

It deliberately does NOT check anything domain-specific. Crossfoot identities,
tie-outs, tag coverage and label honesty belong in the module's own validate
script, because they reference that module's metrics. This runs alongside that
script, not instead of it.

Comparison uses `git diff --quiet <baseline> -- <path>`, which is
line-ending-aware. Hashing the working tree instead would fail on every run on
Windows the moment a tool rewrote a file with CRLF — a failure about nothing.

Usage:
    python src/validate_freeze.py                 # uses governance/freeze.toml
    python src/validate_freeze.py --config <path>
    python src/validate_freeze.py --report <path> # also write a markdown report

Exit code 0 = freeze intact. Exit code 1 = publish nothing, commit nothing.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import tomllib
from datetime import date
from pathlib import Path

TEMPLATE_VERSION = "1.0.0"

# A gate that crashes while printing its own PASS line reports failure to
# anything reading the exit code. The Windows console defaults to cp1252, which
# cannot encode the en dashes and minus signs in these reports, so a clean run
# died with UnicodeEncodeError and exit 1. Never let formatting decide the
# verdict.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")


def repo_root(start: Path) -> Path:
    """The git top level containing `start`."""
    r = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        cwd=start, capture_output=True, text=True,
    )
    if r.returncode != 0:
        sys.exit(f"not inside a git repository: {start}")
    return Path(r.stdout.strip())


def git_ok(root: Path, *args: str) -> bool:
    return subprocess.run(["git", *args], cwd=root, capture_output=True).returncode == 0


def resolve(root: Path, patterns: list[str]) -> tuple[list[str], list[str]]:
    """Expand glob patterns to repo-relative paths.

    Returns (paths, empty_patterns). A pattern that matches nothing is
    reported rather than ignored: a frozen file that has been deleted or
    renamed is exactly the kind of change this gate exists to catch, and a
    silently-empty protected list would pass with zero checks.
    """
    found: set[str] = set()
    empty: list[str] = []
    for pattern in patterns:
        matches = [
            p for p in root.glob(pattern)
            if p.is_file() and ".git" not in p.parts
        ]
        if not matches:
            empty.append(pattern)
        for p in matches:
            found.add(p.relative_to(root).as_posix())
    return sorted(found), empty


def load_config(root: Path, config: str | None = None) -> dict:
    """Parse the module's freeze.toml."""
    path = Path(config) if config else root / "governance" / "freeze.toml"
    if not path.exists():
        sys.exit(f"no freeze config at {path} — see cascadia-standards/templates/freeze.example.toml")
    return tomllib.loads(path.read_text(encoding="utf-8"))


def load_protected(root: Path, config: str | None = None) -> tuple[list[str], str]:
    """The module's protected paths and baseline, for reuse by its own validator.

    Exposed so a module's domain validation script can report freeze integrity
    in its own report without keeping a second copy of the protected-path list.
    Two copies of that list is precisely how they drift apart unnoticed.
    """
    cfg = load_config(root, config)
    freeze = cfg.get("freeze", {})
    paths, _ = resolve(root, freeze.get("protected_paths", []))
    exempt = {e["path"] for e in cfg.get("permitted_edit", [])}
    return [p for p in paths if p not in exempt], freeze.get("baseline", "HEAD")


def main() -> int:
    ap = argparse.ArgumentParser(description="Cascadia freeze-integrity gate.")
    ap.add_argument("--config", default=None, help="path to freeze.toml")
    ap.add_argument("--report", default=None, help="also write a markdown report here")
    args = ap.parse_args()

    root = repo_root(Path(__file__).resolve().parent)
    cfg = load_config(root, args.config)
    freeze = cfg.get("freeze", {})
    module = freeze.get("module", root.name)
    as_of = freeze.get("as_of_date", "<unset>")
    baseline = freeze.get("baseline", "HEAD")
    protected_patterns = freeze.get("protected_paths", [])
    permitted = cfg.get("permitted_edit", [])

    if not protected_patterns:
        sys.exit(f"{cfg_path}: freeze.protected_paths is empty — nothing would be checked")

    if not git_ok(root, "rev-parse", "--verify", f"{baseline}^{{commit}}"):
        sys.exit(f"baseline '{baseline}' is not a commit this repo knows about")

    protected, empty_patterns = resolve(root, protected_patterns)
    exempt = {e["path"] for e in permitted}
    checked = [p for p in protected if p not in exempt]

    changed = [p for p in checked if not git_ok(root, "diff", "--quiet", baseline, "--", p)]

    # A declared exemption that isn't actually a protected path is a config bug:
    # it reads as though something is being carefully allowed when nothing is.
    stray = sorted(exempt - set(protected))

    failures: list[str] = []
    failures += [f"CHANGED since {baseline}: {p}" for p in changed]
    failures += [f"protected_paths pattern matches nothing: {p}" for p in empty_patterns]
    failures += [f"permitted_edit path is not a protected path: {p}" for p in stray]
    ok = not failures

    print(f"Cascadia freeze gate (template v{TEMPLATE_VERSION}) — {module}")
    print(f"  as-of      {as_of}")
    print(f"  baseline   {baseline}")
    print(f"  protected  {len(checked)} paths checked, {len(exempt)} exempt")
    for e in permitted:
        print(f"  EXEMPT     {e['path']} — {e.get('reason', 'no reason recorded')}")
    for f in failures:
        print(f"  FAIL       {f}")

    if args.report:
        lines = [
            f"# Freeze-integrity report — {module}",
            "",
            f"*Generated by `validate_freeze.py` (cascadia-standards template "
            f"v{TEMPLATE_VERSION}) on {date.today().isoformat()}.*",
            "",
            f"**Overall: {'FREEZE INTACT' if ok else 'FREEZE VIOLATED'}**",
            "",
            f"- Frozen as-of **{as_of}**",
            f"- Compared against **{baseline}**",
            f"- **{len(checked)}** protected paths checked, **{len(exempt)}** declared exempt",
            "",
        ]
        if permitted:
            lines += ["## Declared exemptions", ""]
            lines += [f"- `{e['path']}` — {e.get('reason', 'no reason recorded')}" for e in permitted]
            lines += [""]
        if failures:
            lines += ["## Failures", ""] + [f"- {f}" for f in failures] + [""]
        Path(args.report).write_text("\n".join(lines), encoding="utf-8")
        print(f"  wrote      {args.report}")

    if not ok:
        print("\nPUBLISH GATE: FAILED — the freeze is not intact. Publish nothing, commit nothing.")
        return 1
    print("\nPUBLISH GATE: PASSED — freeze intact.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
